# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{outfox}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["TJ Stankus"]
  s.date = %q{2009-12-23}
  s.default_executable = %q{outfox}
  s.description = %q{Create OFX files from PDF bank statements}
  s.email = %q{tj@stank.us}
  s.executables = ["outfox"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/outfox",
     "doc/outfox.taskpaper",
     "features/command_line.feature",
     "features/ofx.feature",
     "features/step_definitions/account_steps.rb",
     "features/step_definitions/command_line_steps.rb",
     "features/step_definitions/ofx_steps.rb",
     "features/support/env.rb",
     "lib/outfox.rb",
     "lib/outfox/error_messages.rb",
     "lib/outfox/messages.rb",
     "lib/outfox/parser.rb",
     "lib/outfox/receivers/wachovia_checking_statement.rb",
     "outfox.gemspec",
     "spec/config/account_info_example.yml",
     "spec/fixtures/minimal_valid_1.pdf",
     "spec/fixtures/minimal_valid_2.pdf",
     "spec/fixtures/test.txt",
     "spec/outfox/parser_spec.rb",
     "spec/outfox/receivers/wachovia_checking_statement_receiver_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tjstankus/outfox}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Create OFX files from PDF bank statements}
  s.test_files = [
    "spec/outfox/parser_spec.rb",
     "spec/outfox/receivers/wachovia_checking_statement_receiver_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

